// Service worker (generated by scripts/pwa.mjs): the app opens offline.
// Pages: network first, so an update shows up on the next open; the cached
// copy is used only without network, and only a good (200) page is cached.
// Other files: cache first — the script bundle's name changes with every
// build, and a new build installs a new cache with fresh copies of the rest.
// Requests to other sites (Lemon Squeezy) are never touched.
const PREFIX = 'flowlab-baby-log-';
const CACHE = PREFIX + '57134dc15c0d';
const FILES = ["./","./apple-touch-icon.png","./expo/static/js/web/index-ece5e3d4c1f5a8df40fc977dc0d3a6d8.js","./favicon.ico","./icon-192.png","./icon-512.png","./manifest.webmanifest","./metadata.json"];
const SHELL = new URL('./', self.location).href;

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(CACHE)
      .then((c) => c.addAll(FILES.map((u) => new Request(u, { cache: 'reload' })))) // not the HTTP cache
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (e) => {
  // Only this app's old caches: another app on the same site keeps its own.
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith(PREFIX) && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req, { cache: 'no-cache' })
        .then((res) => {
          const url = new URL(req.url);
          url.hash = '';
          url.search = '';
          if (res.ok && res.type === 'basic' && (url.href === SHELL || url.href === SHELL + 'index.html')) {
            const copy = res.clone();
            e.waitUntil(caches.open(CACHE).then((c) => c.put(SHELL, copy)));
          }
          return res;
        })
        .catch(() => caches.open(CACHE).then((c) => c.match(SHELL))),
    );
    return;
  }
  e.respondWith(caches.open(CACHE).then((c) => c.match(req)).then((hit) => hit || fetch(req)));
});
